[package]
name = "ufpr-thesis-unofficial"
version = "0.0.1"
entrypoint = "src/lib.typ"
authors = ["Leonardo A. Santos"]
license = "Unlicense"
categories = ["thesis", "layout"]
disciplines = ["computer-science", "engineering", "biology", "chemistry"]
keywords = ["ufpr", "tcc", "thesis", "academic", "university", "paran√°"]
description = "Unofficial UFPR thesis template following ABNT standards"
repository = "https://github.com/Je-Leo-AS/ufpr-thesis-unofficial"
compiler = "0.14.0"
exclude = [
  ".git/",
  ".gitignore",
  ".vscode/",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"